backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'docs(storybook): create {{collection}} "{{slug}}"'
    update: 'docs(storybook): update {{collection}} "{{slug}}"'
    delete: 'docs(storybook): delete {{collection}} "{{slug}}"'
    uploadMedia: 'docs(storybook): upload "{{path}}"'
    deleteMedia: 'docs(storybook): delete "{{path}}"'
    openAuthoring: 'docs(storybook): {{message}}'

media_folder: public/img
public_folder: img

collections:
  - name: "introduction"
    label: "Introduction"
    files:
      - label: "Welcome"
        name: "welcome"
        file: "docs/introduction/1-welcome.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Getting Started"
        name: "getting-started"
        file: "docs/introduction/2.1-getting-started.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "For Designers"
        name: "for-designers"
        file: "docs/introduction/2.2-for-designers.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "For Developers"
        name: "for-developers"
        file: "docs/introduction/2.3-for-developers.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "For Partners"
        name: "for-partners"
        file: "docs/introduction/2.4-for-partners.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "For Quality Testers"
        name: "for-testers"
        file: "docs/introduction/2.5-for-quality-testers.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Governance"
        name: "governance"
        file: "docs/introduction/3.1-governance.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Component Lifecycle"
        name: "component-lifecycle"
        file: "docs/introduction/3.2-component-lifecycle.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Release Process"
        name: "release-process"
        file: "docs/introduction/3.3-release-process.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Atomic Design"
        name: "atomic-design"
        file: "docs/introduction/3.4-atomic-design.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "design-tokens"
    label: "Design Tokens"
    folder: "docs/design-tokens"
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }